package org.firstfolio.content.validation;

public enum LessonValidationErrorCode {
    INVALID_JSON,
    SCHEMA_VERSION_REQUIRED,
    UNSUPPORTED_SCHEMA_VERSION,
    SCHEMA_VIOLATION,
    DUPLICATE_PAGE_ID,
    SUB_CHAPTER_NOT_FOUND,
    REFERENCED_QUESTION_NOT_FOUND,
    QUESTION_NOT_PUBLISHED,
    QUESTION_USAGE_TYPE_MISMATCH,
    QUESTION_SUB_CHAPTER_MISMATCH
}
